### ISSUE TITLE
[FEATURE] 시간여행 뷰 구현 / 폴더링 합시다!

### ISSUE THREAD

**Issue by dn7638** [TeamDearToday/Deartoday-Android#44]
## 📝  To-do

- [ ] TimeTravel View 구현
- [ ] 메인 하위로 패키징 폴더링 어떻게 할 지~?! 승현센세 컨펌받기

## 📆 Date

Dear.220713 To.220714

**Comment by hansh0101** [comment]
이슈 이름은 간결하게 부탁드려요 ^^
