### ISSUE TITLE
[FEATURE] Onboarding 생성 및 연결

### ISSUE THREAD

**Issue by uxri** [TeamDearToday/Deartoday-Android#6]
## 📝  To-do

- [x] Navigation Component 세팅
- [x] Onboarding 생성
- [x] Onboarding Fragment 연결

## 📆 Date

0707 - 0710

**Comment by hansh0101** [comment]
Navigation Component 만들 때 일단 다 만들지 말고 Fragment 전환 간 애니메이션이 잘 동작하는지 1번 온보딩 화면 -> 2번 온보딩화면 테스트를 먼저 해보고 나머지를 이어서 착착 만드는 게 효율적일 듯 !!! 뷰 미리 다 짜놨는데 애니메이션이 말썽이면 뷰를 다시 구성해야 할 수도 있을 것 같단 생각이 드네 !!
